/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Main: typeof import('./src/components/Main.vue')['default']
    Moveable: typeof import('moveable')
  }
}
