/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AButtonGroup: typeof import('ant-design-vue/es')['ButtonGroup']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACol: typeof import('ant-design-vue/es')['Col']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    APageHeader: typeof import('ant-design-vue/es')['PageHeader']
    APopover: typeof import('ant-design-vue/es')['Popover']
    ARadioButton: typeof import('ant-design-vue/es')['RadioButton']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASlider: typeof import('ant-design-vue/es')['Slider']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    AWatermark: typeof import('ant-design-vue/es')['Watermark']
    CanvasDetail: typeof import('./src/components/design-canvas/CanvasDetail.vue')['default']
    Card: typeof import('./src/components/card/Card.vue')['default']
    CheckBox: typeof import('./src/components/checkbox/CheckBox.vue')['default']
    ContentBox: typeof import('./src/components/content-box/ContentBox.vue')['default']
    DefaultEditorDetail: typeof import('./src/components/canvas/DefaultEditorDetail.vue')['default']
    DesignCanvas: typeof import('./src/components/design-canvas/DesignCanvas.vue')['default']
    DividingLine: typeof import('./src/components/dividing-line/DividingLine.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCheckboxButton: typeof import('element-plus/es')['ElCheckboxButton']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    LineGuides: typeof import('./src/components/line-guides/LineGuides.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScaleControl: typeof import('./src/components/scale-control/ScaleControl.vue')['default']
    SliderNumber: typeof import('./src/components/slider-number/SliderNumber.vue')['default']
    WText: typeof import('./src/components/w-text/WText.vue')['default']
    WTextDetail: typeof import('./src/components/w-text/WTextDetail.vue')['default']
  }
}
